/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Color;
import static java.awt.Color.red;
import static java.awt.Color.white;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author Ly Thanh Hai
 */
public class weatherApp1 extends javax.swing.JFrame {

    /**
     * Creates new form weatherApp1
     */
    public weatherApp1() {
        initComponents();
    }
  public class jPanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(181,136,247);
            Color color2 = new Color(29,229,226);
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0,0,width,height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        p3 = new jPanelGradient();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        label2 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        description2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        lastestLocation = new javax.swing.JButton();
        l5 = new javax.swing.JLabel();
        parentLayout = new javax.swing.JPanel();
        newAndEventLayout = new javax.swing.JPanel();
        weatherLayout = new jPanelGradient();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        label1 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        description1 = new javax.swing.JLabel();
        parentLayOut = new javax.swing.JPanel();
        GalleryLayout = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Weather = new javax.swing.JLabel();
        Gallery = new javax.swing.JLabel();
        newsAndEvents = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 60));

        jLabel26.setText("galle");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel27.setText("wea");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        jLabel28.setText("new");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel27)
                .addGap(127, 127, 127)
                .addComponent(jLabel28)
                .addGap(135, 135, 135)
                .addComponent(jLabel26)
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(921, 212));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        p3.setForeground(new java.awt.Color(240, 240, 240));
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel29.setText("Mon");
        jLabel29.setPreferredSize(new java.awt.Dimension(30, 25));
        p3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 40, -1));

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel30.setText("Tue");
        jLabel30.setPreferredSize(new java.awt.Dimension(30, 25));
        p3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel31.setText("Wed");
        jLabel31.setPreferredSize(new java.awt.Dimension(35, 25));
        p3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 45, -1));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel32.setText("Thu");
        jLabel32.setMaximumSize(new java.awt.Dimension(30, 25));
        jLabel32.setPreferredSize(new java.awt.Dimension(30, 25));
        p3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel33.setText("Fri");
        jLabel33.setPreferredSize(new java.awt.Dimension(30, 25));
        p3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel34.setText("Sat");
        jLabel34.setPreferredSize(new java.awt.Dimension(30, 25));
        p3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel35.setText("Sun");
        p3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Sun-CloudyRain-icon-48px.png")); // NOI18N
        p3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 48));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("28");
        p3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Clouds-icon-28px.png")); // NOI18N
        p3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("30");
        p3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Clouds-icon-28px.png")); // NOI18N
        p3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("30");
        p3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel42.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Sun-icon-28px.png")); // NOI18N
        p3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 48));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("32");
        p3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Sun-icon-28px.png")); // NOI18N
        p3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, 48));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("34");
        p3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel46.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Clouds-icon-28px.png")); // NOI18N
        p3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, 48));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("29");
        p3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel48.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Rain-icon-48px.png")); // NOI18N
        p3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("26");
        p3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        p3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 22, -1, 126));

        label2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 51));
        label2.setText("60 ");
        p3.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        icon2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        icon2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Rain-icon-48px.png")); // NOI18N
        p3.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        date2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        date2.setText("Thu,6");
        p3.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        description2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        description2.setText("description");
        p3.add(description2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jPanel4.setPreferredSize(new java.awt.Dimension(936, 631));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(936, 631));

        jPanel1.setPreferredSize(new java.awt.Dimension(936, 631));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Weather App");
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        l3.setBackground(new java.awt.Color(255, 255, 255));
        l3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\location-icon-64px-beau.png")); // NOI18N
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, -1));

        label3.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Quang Tri, Viet Nam");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        lastestLocation.setBackground(new java.awt.Color(0, 255, 51));
        lastestLocation.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lastestLocation.setText("Lastest Locations");
        lastestLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastestLocationMouseClicked(evt);
            }
        });
        jPanel1.add(lastestLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 190, 40));

        l5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Badge-multiply-icon-24px-red.png")); // NOI18N
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, -1));

        parentLayout.setLayout(new java.awt.CardLayout());

        newAndEventLayout.setBackground(new java.awt.Color(0, 255, 153));

        javax.swing.GroupLayout newAndEventLayoutLayout = new javax.swing.GroupLayout(newAndEventLayout);
        newAndEventLayout.setLayout(newAndEventLayoutLayout);
        newAndEventLayoutLayout.setHorizontalGroup(
            newAndEventLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        newAndEventLayoutLayout.setVerticalGroup(
            newAndEventLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        parentLayout.add(newAndEventLayout, "card3");

        weatherLayout.setForeground(new java.awt.Color(240, 240, 240));
        weatherLayout.setPreferredSize(new java.awt.Dimension(921, 400));
        weatherLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("Mon");
        jLabel4.setPreferredSize(new java.awt.Dimension(30, 25));
        weatherLayout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 40, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setText("Tue");
        jLabel5.setPreferredSize(new java.awt.Dimension(30, 25));
        weatherLayout.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel6.setText("Wed");
        jLabel6.setPreferredSize(new java.awt.Dimension(35, 25));
        weatherLayout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 45, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel7.setText("Thu");
        jLabel7.setMaximumSize(new java.awt.Dimension(30, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 25));
        weatherLayout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel8.setText("Fri");
        jLabel8.setPreferredSize(new java.awt.Dimension(30, 25));
        weatherLayout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel9.setText("Sat");
        jLabel9.setPreferredSize(new java.awt.Dimension(30, 25));
        weatherLayout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel10.setText("Sun");
        weatherLayout.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Sun-CloudyRain-icon-48px.png")); // NOI18N
        weatherLayout.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 48));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("28");
        weatherLayout.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Clouds-icon-28px.png")); // NOI18N
        weatherLayout.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("30");
        weatherLayout.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Clouds-icon-28px.png")); // NOI18N
        weatherLayout.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("30");
        weatherLayout.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Sun-icon-28px.png")); // NOI18N
        weatherLayout.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 48));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("32");
        weatherLayout.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Sun-icon-28px.png")); // NOI18N
        weatherLayout.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, 48));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("34");
        weatherLayout.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Clouds-icon-28px.png")); // NOI18N
        weatherLayout.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, 48));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("29");
        weatherLayout.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Rain-icon-48px.png")); // NOI18N
        weatherLayout.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("26");
        weatherLayout.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        weatherLayout.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 22, -1, 126));

        label1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setText("60 ");
        weatherLayout.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        icon1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        icon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\icon\\Weather-Rain-icon-48px.png")); // NOI18N
        weatherLayout.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        date1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        date1.setText("Thu,6");
        weatherLayout.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        description1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        description1.setText("description");
        weatherLayout.add(description1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        parentLayOut.setBackground(new java.awt.Color(255, 51, 51));
        parentLayOut.setLayout(new java.awt.CardLayout());
        weatherLayout.add(parentLayOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        parentLayout.add(weatherLayout, "card4");

        GalleryLayout.setBackground(new java.awt.Color(204, 153, 0));

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0,90));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout GalleryLayoutLayout = new javax.swing.GroupLayout(GalleryLayout);
        GalleryLayout.setLayout(GalleryLayoutLayout);
        GalleryLayoutLayout.setHorizontalGroup(
            GalleryLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        GalleryLayoutLayout.setVerticalGroup(
            GalleryLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        parentLayout.add(GalleryLayout, "card2");

        jPanel1.add(parentLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 920, 210));

        Weather.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Weather.setForeground(new java.awt.Color(240, 240, 240));
        Weather.setText("Weather");
        Weather.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WeatherMousePressed(evt);
            }
        });
        jPanel1.add(Weather, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        Gallery.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Gallery.setForeground(new java.awt.Color(240, 240, 240));
        Gallery.setText("Gallery");
        Gallery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GalleryMousePressed(evt);
            }
        });
        jPanel1.add(Gallery, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        newsAndEvents.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        newsAndEvents.setForeground(new java.awt.Color(240, 240, 240));
        newsAndEvents.setText("News and Events");
        newsAndEvents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newsAndEventsMousePressed(evt);
            }
        });
        jPanel1.add(newsAndEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("City :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 60));

        txt1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 30));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, 30));

        l2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ly Thanh Hai\\OneDrive\\Documents\\image\\Background.png")); // NOI18N
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String latestLocation;
    private void lastestLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastestLocationMouseClicked
        String city1 = latestLocation;
        String[] res = city1.trim().split(" ");
        String city2 = "";
        for(int i=0;i<res.length;i++)
        {
            city2+=res[i];
        }
        try{
            String uri=String.format("http://api.openweathermap.org/data/2.5/forecast?q=%s&APPID=685ebafde2aa0591bc76bf26895660c5&units=metric",city2);
            String url = uri;
            URL obj=new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            int responseCode = con.getResponseCode();
            //        System.out.println("URL :" +url);
            //        System.out.println(responseCode);
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();
            while((inputLine=in.readLine()) != null)
            {
                response.append(inputLine);
            }
            in.close();

            //        System.out.println(response);
            //        System.out.println(response.toString());
            JSONObject myresponse = new JSONObject(response.toString());

            JSONObject cityObject = new JSONObject(myresponse.getJSONObject("city").toString());
            //             JSONObject tempObject = new JSONObject(myresponse.getJSONObject("list").getJSONObject("0").getJSONObject("main").toString());
            JSONArray listArray =myresponse.getJSONArray("list");
            JSONObject Object =listArray.getJSONObject(2);
            JSONObject mainObject =Object.getJSONObject("main");
            JSONArray weatherArray =Object.getJSONArray("weather");
            JSONObject weatherObject =weatherArray.getJSONObject(0);
            String temp = String.valueOf(mainObject.getDouble("temp"));
            //lấy icon
            String iconUri=weatherObject.getString("icon");
            String description = weatherObject.getString("description");
            // setIcon.
            String URL1 = String.format("http://openweathermap.org/img/wn/" + iconUri + "@2x.png");
            //          ImageIcon image = new ImageIcon(URL);
            //          icon1.setIcon(image);
            // setIconMethod2.
            try {
                BufferedImage img = ImageIO.read(new URL(URL1));
                Image img1 = img.getScaledInstance(icon1.getWidth(),icon1.getHeight(), Image.SCALE_SMOOTH);
                icon1.setIcon(new javax.swing.ImageIcon(img1));

            }
            catch(IOException ex) {
                System.err.println("error");
            }
            String lastestLocation = cityObject.getString("name");
            description1.setText(description);
            label1.setText(temp+"°C");
            date1.setText(Object.getString("dt_txt"));
            label3.setText(cityObject.getString("name") + ", " + cityObject.getString("country") );
            //        icon1.
            //              System.out.println("temp :" +tempObject.getInt("temp"));
            //System.out.println("temp :" +listObject.getInt("temp"));
        }
        catch(Exception e)
        {System.out.println(e);}
    }//GEN-LAST:event_lastestLocationMouseClicked

    private void WeatherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WeatherMousePressed
        Weather.setText("Weather");
        Weather.setForeground(red);
        newsAndEvents.setForeground(white);
        Gallery.setForeground(white);
        parentLayOut.removeAll();
        parentLayOut.add(weatherLayout);
        parentLayOut.repaint();
        parentLayOut.revalidate();
    }//GEN-LAST:event_WeatherMousePressed

    private void GalleryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GalleryMousePressed
        Gallery.setText("Gallery");
        Gallery.setForeground(red);
        newsAndEvents.setForeground(white);
        Weather.setForeground(white);
        parentLayOut.removeAll();
        parentLayOut.add(GalleryLayout);
        parentLayOut.repaint();
        parentLayOut.revalidate();
    }//GEN-LAST:event_GalleryMousePressed

    private void newsAndEventsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsAndEventsMousePressed
        newsAndEvents.setText("News and events");
        newsAndEvents.setForeground(red);
        Gallery.setForeground(white);
        Weather.setForeground(white);
        parentLayOut.removeAll();
        parentLayOut.add(newAndEventLayout);
        parentLayOut.repaint();
        parentLayOut.revalidate();
    }//GEN-LAST:event_newsAndEventsMousePressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String city1;
        city1 = txt1.getText();
        String[] city2 = city1.split(" ");
        String city="";
        if(city2.length>=2){for(int i=0;i<city2.length;i++){city+=city2[i];}}
        else city=city1;
        try{
            String uri=String.format("http://api.openweathermap.org/data/2.5/forecast?q=%s&APPID=685ebafde2aa0591bc76bf26895660c5&units=metric",city);
            String url = uri;
            URL obj=new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            int responseCode = con.getResponseCode();
            //        System.out.println("URL :" +url);
            //        System.out.println(responseCode);
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();
            while((inputLine=in.readLine()) != null)
            {
                response.append(inputLine);
            }
            in.close();

            //        System.out.println(response);
            //        System.out.println(response.toString());
            JSONObject myresponse = new JSONObject(response.toString());

            JSONObject cityObject = new JSONObject(myresponse.getJSONObject("city").toString());
            //             JSONObject tempObject = new JSONObject(myresponse.getJSONObject("list").getJSONObject("0").getJSONObject("main").toString());
            JSONArray listArray =myresponse.getJSONArray("list");
            JSONObject Object =listArray.getJSONObject(2);
            JSONObject mainObject =Object.getJSONObject("main");
            JSONArray weatherArray =Object.getJSONArray("weather");
            JSONObject weatherObject =weatherArray.getJSONObject(0);
            String temp = String.valueOf(mainObject.getDouble("temp"));
            //lấy icon
            String iconUri=weatherObject.getString("icon");
            String description = weatherObject.getString("description");
            // setIcon.
            String URL1 = String.format("http://openweathermap.org/img/wn/" + iconUri + "@2x.png");
            //          ImageIcon image = new ImageIcon(URL);
            //          icon1.setIcon(image);
            // setIconMethod2.
            try {
                BufferedImage img = ImageIO.read(new URL(URL1));
                Image img1 = img.getScaledInstance(icon1.getWidth(),icon1.getHeight(), Image.SCALE_SMOOTH);
                icon1.setIcon(new javax.swing.ImageIcon(img1));

            }
            catch(IOException ex) {
                System.err.println("error");
            }
            latestLocation = cityObject.getString("name");
            description1.setText(description);
            label1.setText(temp+"°C");
            date1.setText(Object.getString("dt_txt"));
            label3.setText(cityObject.getString("name") + ", " + cityObject.getString("country") );
            //        icon1.
            //              System.out.println("temp :" +tempObject.getInt("temp"));
            //System.out.println("temp :" +listObject.getInt("temp"));
        }
        catch(Exception e)
        {System.out.println(e);}
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
//        parentLayOut.removeAll();
//        parentLayOut.add(jPanel5);
//        parentLayOut.repaint();
//        parentLayOut.revalidate();
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
//        parentLayOut.removeAll();
//        parentLayOut.add(jPanel3);
//        parentLayOut.repaint();
//        parentLayOut.revalidate();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
//        parentLayOut.removeAll();
//        parentLayOut.add(jPanel4);
//        parentLayOut.repaint();
//        parentLayOut.revalidate();
    }//GEN-LAST:event_jLabel28MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(weatherApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(weatherApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(weatherApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(weatherApp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new weatherApp1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gallery;
    private javax.swing.JPanel GalleryLayout;
    private javax.swing.JLabel Weather;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel description2;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JButton lastestLocation;
    private javax.swing.JPanel newAndEventLayout;
    private javax.swing.JLabel newsAndEvents;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel parentLayOut;
    private javax.swing.JPanel parentLayout;
    private javax.swing.JTextField txt1;
    private javax.swing.JPanel weatherLayout;
    // End of variables declaration//GEN-END:variables
}
